//////// ESTABLISHES GLOBAL SET OF VALUES THAT COMPONENTS USE WITH PASSING EACH INDIVIDUALLY DOWN THE LINE. ////////

export const SET_LOADING = 'SET_LOADING'

export const ADD_READER_SUCCESS = 'ADD_READER_SUCCESS'
export const ADD_READER_ERROR = 'ADD_READER_ERROR'
export const SET_READER = 'SET_READER'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR'
export const LOGOUT_READER = 'LOGOUT_READER'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR'
export const FETCH_SINGLE_JOB_SUCCESS = 'FETCH_SINGLE_JOB_SUCCESS'
export const FETCH_SINGLE_JOB_ERROR = 'FETCH_SINGLE_JOB_ERROR'

export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'
